FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    && apt-get clean

RUN pip install kafka-python

COPY kafka_topic_creator.py .

CMD ["python", "kafka_topic_creator.py"]
