FROM bitnami/spark:latest

COPY ./spark_consumer/spark_consumer.py /opt/spark-apps/

ENV SPARK_MODE=driver

CMD ["spark-submit", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1,org.apache.kafka:kafka-clients:3.7.0", "/opt/spark-apps/spark_consumer.py"]
