FROM python:3.9-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    build-essential \
    && apt-get clean

RUN pip install kafka-python pandas schedule

CMD ["python", "message_producer.py"]